version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mongo:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  app:
    build: .
    container_name: job-importer-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    restart: unless-stopped
    # For development mounts, uncomment the volume below to reflect local changes inside container
    # volumes:
    #   - ./:/usr/src/app

  worker:
    build: .
    container_name: job-importer-worker
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    command: ["npm", "run", "worker"]
    restart: unless-stopped

volumes:
  redis-data:
  mongo-data: